# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """Настройки инициализации"""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 617)

        #Главный виджет
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #TabWidget Главное меню
        self.MainMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.MainMenu.setGeometry(QtCore.QRect(-10, -30, 821, 651))
        self.MainMenu.setToolTip("")
        self.MainMenu.setStyleSheet("background-color: #22222e")
        self.MainMenu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainMenu.setTabsClosable(True)
        self.MainMenu.setMovable(False)
        self.MainMenu.setObjectName("MainMenu")

        #Страница меню
        self.menu = QtWidgets.QWidget()
        self.menu.setStyleSheet("background-color: #22222e")
        self.menu.setObjectName("menu")

        #Кнопка 1-ого задания
        self.btn1 = QtWidgets.QPushButton(self.menu)
        self.btn1.setGeometry(QtCore.QRect(230, 180, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("QPushButton {\n"
                                "    background-color: #22222e;\n"
                                "    border: 2px solid #f66867;\n"
                                "    border-radius: 30;\n"
                                "    color: white;\n"
                                "}\n"
                                "\n"
                                "QPushButton: pressed {\n"
                                "    background-color: #0d0d12\n"
                                "}")
        self.btn1.setObjectName("btn1")

        #Кнопка 2-ого задания
        self.btn2 = QtWidgets.QPushButton(self.menu)
        self.btn2.setGeometry(QtCore.QRect(230, 270, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("QPushButton {\n"
                                "    background-color: #22222e;\n"
                                "    border: 2px solid #f66867;\n"
                                "    border-radius: 30;\n"
                                "    color: white;\n"
                                "}\n"
                                "\n"
                                "QPushButton: pressed {\n"
                                "    background-color: #0d0d12\n"
                                "}")
        self.btn2.setObjectName("btn2")

        #Кнопка 3-его задания
        self.btn3 = QtWidgets.QPushButton(self.menu)
        self.btn3.setGeometry(QtCore.QRect(230, 360, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setToolTip("Алекперов Низами Джасурович \nИУК4-32Б")
        self.btn3.setStyleSheet("QPushButton {\n"
                                "    background-color: #22222e;\n"
                                "    border: 2px solid #f66867;\n"
                                "    border-radius: 30;\n"
                                "    color: white;\n"
                                "}\n"
                                "\n"
                                "QPushButton: pressed {\n"
                                "    background-color: #0d0d12\n"
                                "}")
        self.btn3.setObjectName("btn3")

        #Кнопка выхода из приложения
        self.btnexit1 = QtWidgets.QPushButton(self.menu)
        self.btnexit1.setGeometry(QtCore.QRect(700, 580, 110, 30))
        self.btnexit1.setStyleSheet("QPushButton {\n"
                                    "    background-color: #22222e;\n"
                                    "    border: 2px solid #f66867;\n"
                                    "    color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton: pressed {\n"
                                    "    background-color: #0d0d12\n"
                                    "}")
        self.btnexit1.setObjectName("btnexit1")

        #Заглавный текст
        self.lab1 = QtWidgets.QLabel(self.menu)
        self.lab1.setGeometry(QtCore.QRect(230, 90, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lab1.setFont(font)
        self.lab1.setStyleSheet("color: white;\n"
                                "background-color: #fb5b5d;")
        self.lab1.setAlignment(QtCore.Qt.AlignCenter)
        self.lab1.setObjectName("lab1")

        #TabWidget Страница графика
        self.MainMenu.addTab(self.menu, "")
        self.graphic = QtWidgets.QWidget()
        self.graphic.setObjectName("graphic")

        #Кнопка выхода в главное меню
        self.btnexit2 = QtWidgets.QPushButton(self.graphic)
        self.btnexit2.setGeometry(QtCore.QRect(700, 580, 110, 30))
        self.btnexit2.setStyleSheet("QPushButton {\n"
                                    "    background-color: #22222e;\n"
                                    "    background-color: #22222e;\n"
                                    "    border: 2px solid #f66867;\n"
                                    "    color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton: pressed {\n"
                                    "    background-color: #0d0d12\n"
                                    "}")
        self.btnexit2.setObjectName("btnexit2")

        self.widget = QtWidgets.QWidget(self.graphic)
        self.widget.setGeometry(QtCore.QRect(10, 10, 810, 560))
        self.widget.setObjectName("widget")

        #TabWidget Страница склада
        self.MainMenu.addTab(self.graphic, "")
        self.warehouse = QtWidgets.QWidget()
        self.warehouse.setObjectName("warehouse")

        #Кнопка выхода в главное меню
        self.btnexit3 = QtWidgets.QPushButton(self.warehouse)
        self.btnexit3.setGeometry(QtCore.QRect(700, 580, 110, 30))
        self.btnexit3.setStyleSheet("QPushButton {\n"
                                    "    background-color: #22222e;\n"
                                    "    border: 2px solid #f66867;\n"
                                    "    color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton: pressed {\n"
                                    "    background-color: #0d0d12\n"
                                    "}")
        self.btnexit3.setObjectName("btnexit3")

        #Ввод текста "Пополнить"
        self.le1 = QtWidgets.QLineEdit(self.warehouse)
        self.le1.setGeometry(QtCore.QRect(120, 310, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le1.setFont(font)
        self.le1.setStyleSheet("color: white")
        self.le1.setText("")
        self.le1.setAlignment(QtCore.Qt.AlignCenter)
        self.le1.setObjectName("le1")

        #Ввод текста "Купить"
        self.le2 = QtWidgets.QLineEdit(self.warehouse)
        self.le2.setGeometry(QtCore.QRect(540, 310, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le2.setFont(font)
        self.le2.setStyleSheet("color: white")
        self.le2.setText("")
        self.le2.setAlignment(QtCore.Qt.AlignCenter)
        self.le2.setObjectName("le2")

        #Вывод количества товара на складе
        self.lab2 = QtWidgets.QLabel(self.warehouse)
        self.lab2.setGeometry(QtCore.QRect(330, 310, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab2.setFont(font)
        self.lab2.setStyleSheet("color: white;\n"
                                "background-color: #fb5b5d;")
        self.lab2.setText("")
        self.lab2.setAlignment(QtCore.Qt.AlignCenter)
        self.lab2.setObjectName("lab2")

        #Текст "В наличии"
        self.lab3 = QtWidgets.QLabel(self.warehouse)
        self.lab3.setGeometry(QtCore.QRect(330, 250, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab3.setFont(font)
        self.lab3.setStyleSheet("color: white;\n"
                                "background-color: #fb5b5d;")
        self.lab3.setAlignment(QtCore.Qt.AlignCenter)
        self.lab3.setObjectName("lab3")

        #Кнопка "Пополнить"
        self.btn4 = QtWidgets.QPushButton(self.warehouse)
        self.btn4.setGeometry(QtCore.QRect(120, 250, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("QPushButton {\n"
                                "    background-color: #22222e;\n"
                                "    border: 2px solid #f66867;\n"
                                "    border-radius: 30;\n"
                                "    color: white;\n"
                                "}\n"
                                "\n"
                                "QPushButton: pressed {\n"
                                "    background-color: #0d0d12\n"
                                "}")
        self.btn4.setObjectName("btn4")

        #Кнопка "Купить"
        self.btn5 = QtWidgets.QPushButton(self.warehouse)
        self.btn5.setGeometry(QtCore.QRect(540, 250, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("QPushButton {\n"
                                "    background-color: #22222e;\n"
                                "    border: 2px solid #f66867;\n"
                                "    border-radius: 30;\n"
                                "    color: white;\n"
                                "}\n"
                                "\n"
                                "QPushButton: pressed {\n"
                                "    background-color: #0d0d12\n"
                                "}")
        self.btn5.setObjectName("btn5")

        #Текст после совершения операции
        self.lab4 = QtWidgets.QLabel(self.warehouse)
        self.lab4.setGeometry(QtCore.QRect(120, 370, 611, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab4.setFont(font)
        self.lab4.setStyleSheet("color: white;\n"
                                "background-color: #fb5b5d;")
        self.lab4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lab4.setAlignment(QtCore.Qt.AlignCenter)
        self.lab4.setObjectName("lab4")
        self.lab4.setHidden(True)

        self.MainMenu.addTab(self.warehouse, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """Текст в элементах"""
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Домашняя работа №1"))
        self.btn1.setText(_translate("MainWindow", "Задание №1 (График)"))
        self.btn2.setText(_translate("MainWindow", "Задание №2 (Склад)"))
        self.btn3.setText(_translate("MainWindow", "Задание №3 (Справка)"))
        self.btnexit1.setText(_translate("MainWindow", "Выход"))
        self.lab1.setText(_translate("MainWindow", "Основы PyQt"))
        self.MainMenu.setTabText(self.MainMenu.indexOf(self.menu), _translate("MainWindow", "menu"))
        self.btnexit2.setText(_translate("MainWindow", "Назад"))
        self.MainMenu.setTabText(self.MainMenu.indexOf(self.graphic), _translate("MainWindow", "graphic"))
        self.btnexit3.setText(_translate("MainWindow", "Назад"))
        self.lab3.setText(_translate("MainWindow", "В наличии"))
        self.btn4.setText(_translate("MainWindow", "Пополнить"))
        self.btn5.setText(_translate("MainWindow", "Купить"))
        self.lab4.setText(_translate("MainWindow", "Недостаточно товара на складе!"))
        self.MainMenu.setTabText(self.MainMenu.indexOf(self.warehouse), _translate("MainWindow", "warehouse"))
